### ISSUE TITLE
Development: werken met database migrations en seeds

### ISSUE THREAD

**Issue by Linths** [robinklaassen/aas2#1]

**Comment by Linths** [comment]
@robinklaassen zou je dit willen verduidelijken?

**Comment by blackshadev** [comment]
@robinklaassen  Had je dit niet all? Want `php artisan migrate --seed` werkte prima. Of bedoelde je wat anders

**Comment by robinklaassen** [comment]
Het commando werkt inderdaad. De migrations (tabelstructuur) heb ik vorige week gefixt, zodat ze nu hetzelfde resultaat produceren als er nu op productie staat. Alleen nog niet alle tabellen hebben een seed, en ik vermoed dat we ook niet voor alle mogelijke testcases nu geschikte data hebben vanuit de seeds. Dus het gaat nu eigenlijk vooral om het uitbreiden van de seeds.

**Comment by blackshadev** [comment]
Top.
Laat anders even in  weten welke test cases je mist , in welke tabellen en
welke files men in moet kijken.
Dan kunnen wellicht meer mensen wat seeds schrijven, iets met vele handen
ofzo.

**Comment by robinklaassen** [comment]
Ik heb zelf helaas niet zo uit mijn hoofd een compleet beeld van test cases, dus misschien kunnen we definition of done voor deze beter aanpassen naar: **iedere tabel (inclusief draaitabellen) zijn voorzien van seeds met minstens drie unieke records.** 

Als we dan later test cases tegenkomen die we niet kunnen afvangen met de huidige seeds, dan vullen we die aan.

De seeder files staan in `database/seeds`.

**Comment by robinklaassen** [comment]
Aantal seeds toegevoegd in #31 , daarmee kan deze wat mij betreft worden gesloten voor nu.
