### ISSUE TITLE
Login: wachtwoorden versleutelen voor versturen

### ISSUE THREAD

**Issue by Linths** [robinklaassen/aas2#10]
Nu worden wachtwoorden in plaintext in een POST request verstuurd. AAS2.0 werkt met HTTPS dus het zou niet veel problemen moeten leveren, maar eerst versleutelen zou wel netter zijn.

Bron @VXLs

**Comment by blackshadev** [comment]
@VXLs, ik heb aardig wat achtergrond in cryptografie. Veiliger dan een goede HTTPS verbinding ga je niet krijgen. Alle scenarios waar HTTPS tekort schiet (client side attacks) doet dat op client versleutelen ook. Alles in transit ga je niets op winnen want: TLS. 
Wel kan je kijken om je HTTPS sterker te krijgen , dan kan je kijken op https://www.ssllabs.com/ssltest/ hoe "veilig" je bent relatief aan known TLS attacks.

**Comment by VXLs** [comment]
SSL zal in de meeste omstandigheden inderdaad genoeg zijn, maar het is helaas niet onfeilbaar tegen MiM.
Er zou al een hoop winst gehaald worden door HSTS aan te zetten, maar het blijft altijd goed om wantrouwig te zijn tegenover alles wat de ether in gaat.

**Comment by blackshadev** [comment]
HSTS staat aan voor aas2 en www. Kritisch zijn over de data die je verstuurd is nooit erg. Maar onderschat de kracht van TLS niet, de fouten die in TLS zitten zullen in 10 fout in een eigen versleutelingsimplementatie zitten en al dat soort manieren hebben weer hun eigen nadelen om nog niet te spreken over de complexiteit die je introduceert. 
De algehele consensus op het internet hierover is dan ook dat TLS meer dan genoeg is. Als het goed genoeg is om al je privacy op facebook, de bank en je web-mail te garanderen dan zou dat toch ook voldoende moeten zijn voor een administratie systeem van deze vrijwilligers organisatie.
