### ISSUE TITLE
Persoonlijke info: allergieën en dieetwensen 

### ISSUE THREAD

**Issue by Linths** [robinklaassen/aas2#11]
Dit is niet verplicht in te voeren

**Comment by blackshadev** [comment]
Kan iemand even bevestigen dat een allergie of dieet niet onder bijzonder medisch persoonsgegeven valt. Dat is namelijk een dingetje. Dieet denk het niet. maar allergie...

**Comment by blackshadev** [comment]
Volgens het privacy statement : 
```
Wij vragen niet standaard om bijzondere gegevens. Wel vragen wij of er zaken zijn waar wij rekening mee kunnen houden ten tijde van het kamp. Dit kan leiden tot het incidenteel opslaan van bijzondere gegevens, zoals gegevens over gezondheid of dieet. Wij verwerken alleen bijzondere persoonsgegevens als wij dat moeten op basis van de wet, met jouw toestemming of als je dat ons vraagt. In dat laatste geval verwerken wij deze gegevens alleen als dat nodig is voor een goed verloop van het kamp.
```

Om hier een appart veldje te hebben die je dus alleen incidenteel mag gebruiken lijkt me niet handig. De comments hiervoor gebruiken lijkt mij logischer.

Ik sluit de ticket voor nu, mocht dit later wel een wens zijn kan hij altijd heropent worden
