### ISSUE TITLE
Incorrecte toekenning punten voor afgelaste kampen

### ISSUE THREAD

**Issue by robinklaassen** [robinklaassen/aas2#129]
Het puntensysteem telt automatisch de punten voor mensen die op kamp zijn geweest, zodra de einddatum van het kamp is verstreken. Er zijn echter vorig jaar een aantal kampen afgelast, die nog wel in de administratie staan en waar ook leiding aan verbonden is; die krijgen dus nu punten voor een kamp waar ze niet op zijn geweest. Dit moeten we op een of andere manier corrigeren.

Combinerende met #118 zou het logisch zijn om bij ieder kamp een vinkje 'afgelast' (of juist andersom) toe te voegen. We kunnen ook kijken of de kampen uit de administratie verwijderd kunnen worden, maar ik denk dat het goed is voor het historisch besef als we het laten staan.

**Comment by robinklaassen** [comment]
@blackshadev ik wil deze wel binnenkort oppakken, maar ben benieuwd naar jouw mening of zo'n vinkje 'afgelast' voor kampen de beste oplossing is, of dat er misschien nog goede alternatieven zijn :)

**Comment by blackshadev** [comment]
Vinkje is prima, ik zou werl het database veldje als datum neerzeten, is handig dat je weet wanneer hij afgelast is.
