### ISSUE TITLE
Mailadres login i.p.v. usernames

### ISSUE THREAD

**Issue by Linths** [robinklaassen/aas2#13]
Afschaffen aparte usernames (zoals voorletter-achternaam), over op mailadres login.

**Comment by blackshadev** [comment]
Is dit wel wenselijk?
 - Wat als een ouder 2 kinderen (deelnemers) heeft?
 - Wat als een deelnemer gescheiden ouders heeft?
 - Als iemand is vergeten is welk email adres

**Comment by blackshadev** [comment]
Ik sluit de ticket voor nu, mocht dit later wel een wens zijn kan hij altijd heropent worden
