### ISSUE TITLE
Oude deelnemers en leden anonimiseren 

### ISSUE THREAD

**Issue by blackshadev** [robinklaassen/aas2#141]
Een pagina waarin we alle "oude" deelnemers (en leden) selecteren en de mogelijkheid geven om ze te anonimiseren.

Alle persoonsgegevens  moeten verwijderd worden.

**Comment by robinklaassen** [comment]
@blackshadev is deze geclosed door #142 en #146 of moet ie open blijven? Kun je de issue updaten?

**Comment by blackshadev** [comment]
Wauw, 1 maand later: Volgens mij kan deze geclosed worden.
