### ISSUE TITLE
Online kamp en pakket selectie problemen

### ISSUE THREAD

**Issue by blackshadev** [robinklaassen/aas2#150]
Bij het kiezen van het pakket wordt er het verkeerde pakket gebruikt bij de betaling. 
Dit gebeurde bij het lente kamp met deelnemer id 179

Ze wilde graag pakket 1, voor 65 euro, er moest 80 euro worden afgerekend met iDeal en in AAS staat dat ze is ingeschreven voor pakket 3.

- Op productie gereproduceerd door Bouchien.

**Comment by robinklaassen** [comment]
@blackshadev volgens mij kan deze dicht toch? Het foutieve bedrag was volgens mij omdat het kamp zelf ook nog een prijs had, naast de pakketprijzen

**Comment by blackshadev** [comment]
Jup thx voor de housekeeping
