### ISSUE TITLE
Ensure we test on php73 as well

### ISSUE THREAD

**Issue by blackshadev** [robinklaassen/aas2#152]
Our host still runs php 7.3.  Can we upgrade that or alter our deploy script to ensure we use the php73 executable for future deploys. 
And lets also make sure we test on php73 as well...

**Comment by robinklaassen** [comment]
Currently we test on php74 and deploy using php73. Using php73 for testing in Travis throws a segfault that is confirmed  not to be fixed. Only option will be to migrate our CI pipeline, which I believe you're already doing :P

**Comment by blackshadev** [comment]
> Currently we test on php74 and deploy using php73. Using php73 for testing in Travis throws a segfault that is confirmed not to be fixed. Only option will be to migrate our CI pipeline, which I believe you're already doing :P

Your believe is true and our salvation will be here soon. Have faith, we only need to silence the heretic nonbeliever called TravisCI and add a key of trust to our secrets :latin_cross: 

All jokes aside, Almost done, We need to disable travis , add secret keys, merge #156 and test prod deploy

**Comment by robinklaassen** [comment]
Pretty sure this isn't relevant anymore now that we've migrated to use Github Actions with only php 7.4 on our new host.
