### ISSUE TITLE
Leiding ziet online info kampdeelnemers

### ISSUE THREAD

**Issue by Linths** [robinklaassen/aas2#16]
### Huidige situatie
Alleen mensen die horen bij "organisatie" binnen AAS kunnen bij de info van kampdeelnemers. Deze info kan alleen opgehaald worden via een export. De kampcommissie export dus de informatie, en mailen dat door aan de kampleiding.

### Ideale wereld
Leiding opent kamppagina. Leiding ziet deelnemerinfo.

**Comment by blackshadev** [comment]
Hee zover ik kan zien kan iedereen behalve ongeplaatste leden de deelnemers van een kamp zien inclusief 0686723998 en woonplaats.
Voor leiding is dat denk ik prima. Maar nu kan je dus als mee gaande deelnemers ook alles zien, is het een idee om het telefoon nummer weg te halen, enkel de voornaam + eerste letter van de achternaam en het niveau er neer te zetten, als deelnemer heb je meer niet nodig toch?

**Comment by blackshadev** [comment]
Todo
 even controleren of dit niet al kan

**Comment by blackshadev** [comment]
Volgens mij is dit al geïmplementeerd. Zoniet, heropen het ticket vooral
