### ISSUE TITLE
Dashboard leiding

### ISSUE THREAD

**Issue by Linths** [robinklaassen/aas2#17]
Een dashboard voor leiding. Deze moet relevante info duidelijk en overzichtelijk weergeven.

Ideeën:
- "Je gaat binnenkort op dit kamp!"
- Met zoveel deelnemers
- Kamphuislocatie
- Info deelnemers (zie [deze ticket](https://github.com/robinklaassen/aas2/issues/16))
- DRUIF link (zie [deze ticket](https://github.com/robinklaassen/aas2/issues/2))

Een gesprek met de kampcommissie of eigenlijk elk Anderwijslid kan nuttig zijn voor meer ideeën.

**Comment by robinklaassen** [comment]
In de kamp thermometer op de homepage staat nu dat je op kamp gaat, direct linkje naar de kamp pagina met daarop locatie, deelnemers, druif link, ...  dus deze gaat dicht
