### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by blackshadev** [robinklaassen/aas2#176]
Composer huilt: 
```
Package caouecs/laravel-lang is abandoned, you should avoid using it. Use https://github.com/Laravel-Lang/lang instead.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
```

**Comment by robinklaassen** [comment]
`caouecs/laravel-lang` is inmiddels weggehaald uit onze dependencies, deze staat niet meer op packagist en dus raakte onze CI pipeline in het nauw. Volgens mij is er geen alternatief nodig, we hebben eigen vertalingen naar het Nederlands (zie `resources/lang`).

`fzaninotto/faker` wordt niet meer verder ontwikkeld. De auteur is niet oké met de gevolgen van zo'n zwaar package voor het klimaat, volgens zijn blog: https://marmelab.com/blog/2020/10/21/sunsetting-faker.html. Er is wel een fork die actief lijkt: https://github.com/fakerphp/faker, dus wellicht is het zo simpel als deze gebruiken.

**Comment by robinklaassen** [comment]
Gefixt door #181
