### ISSUE TITLE
Laravel upgrade

### ISSUE THREAD

**Issue by blackshadev** [robinklaassen/aas2#24]
AAS2 draait nu op laravel 5.1 , ondertussen is laravel 5.8 al uit en 5.1 wordt al bijna jaar niet meer ondersteund met updates, bug fixes al twee jaar niet meer.

Is er wat voor om alles een voor 1 up te grade naar 5.8, of liever de LTS 5.5 (die overigens dit jaar augustus niet meet ondersteund wordt)

**Comment by robinklaassen** [comment]
Ik had toevallig eerder deze week hetzelfde bedacht om nog als issue toe te voegen! Great minds... ik ben zeker voor. De nieuwe `artisan` heeft ook wat nuttige dingen zoals een `migrate:fresh` optie (ipv `refresh`, werkt net anders). 

Vraag is dan inderdaad nog of we direct naar 5.8 gaan of de 5.5. LTS aanhouden inderdaad. 

Upgraden is niet zo moeilijk (versie aanpassen in `composer.json` en updaten maar), maar er zal nog een boel handmatig getest moeten worden (en het lijkt me goed om dat dan gelijk goed te documenteren).

**Comment by blackshadev** [comment]
Check.

Kijk even goed naar de support termijn van 5.5 , ik vind het schrikbarend
kort; 5.5 krijgt aankomend augustus al geen bugfixes meer.
Ik zou zelf zeggen door naar 5.8 en de volgende release zal vast wel weer
een LTS zijn en dan  kan je daar wel weer ff op voort-teren.

**Comment by blackshadev** [comment]
On it. zie branch [change/upgrade](https://github.com/robinklaassen/aas2/tree/change/upgrade)

Ik ga nu een weekje op vakantie als iemand verder wil, ga je gang!
Ik heb een tussen stap op 5.5 gemaakt maar dit migreren is best wel lastig aangezien laravel het een goed idee vind ik klakkeloos functies te hernoemen, en dingen te veranderen. Waar ik nu tegen aanloop is dat geen enkele datum(tijd) veld uit de models naar Carbon dates worden vertaald en daarom gaan in alle templates the `$model->dateField->format(xx)` fout. 

Ik zelf ben een voorstander van om hierna door te migreren naar 5.8, maar dit is nog niet definities besloten.

**Comment by blackshadev** [comment]
Momenteel zijn er nog wat bugs, men kan mijn PR testen.
