### ISSUE TITLE
Automatische deployment naar productie

### ISSUE THREAD

**Issue by robinklaassen** [robinklaassen/aas2#25]
Hoe ideaal zou het zijn dat na een merge naar master de code automatisch op onze hosting provider wordt gedeployed? Het is nog even de vraag of we het aan de praat krijgen, gezien we naar shared webhosting deployen en niet naar een VPS, maar ik wil kijken hoe ver we kunnen komen met een scripted deployment via Travis (gezien de source public is, is dit ook nog eens gratis).

Plus, het ingericht hebben van Travis maakt het ook nog eens aanlokkelijker om automatisch testen te introduceren.

**Comment by blackshadev** [comment]
Sure ik heb dat soort dingen vaker voor me werk gemaakt. Maar dan via
kubernetes en gitlab.
Maar dit soort dingen maakt het zo veel chiller. Wel moet je dan eigenlijk
ook wat tests enzo introduceren, misschien is dat een goede eerste stap?
PS. Ik heb nog nooit in php tests geschreven, maar dat kan niet moeilijk
zijn met laravel

**Comment by blackshadev** [comment]
SSH key aangemaakt op PC Extreme dus dit moet mogelijk zijn
