### ISSUE TITLE
Mollie upgrade naar v2

### ISSUE THREAD

**Issue by robinklaassen** [robinklaassen/aas2#27]
We gebruiken op dit moment v1.2 van de Mollie API om iDeal betalingen te ondersteunen. v2 is inmiddels al een tijdje uit en hoewel we de nieuwe functionaliteit niet direct nodig hebben, lijkt het me goed om te upgraden. Daarbij kan dan gelijk wat gerefactored worden en een of meerdere tests geschreven.

**Comment by robinklaassen** [comment]
Zie ook https://docs.mollie.com/payments/migrating-v1-to-v2

**Comment by blackshadev** [comment]
Check, zover ik kan zien is het enige wat je  moet veranderen:
De composer.json om de nieuwe API wrapper te pakken `"mollie/mollie-api-php": "^2.0",`
En in de ProfileController.php:487 `"amount"      =>  [ "currency" => "EUR",  "value": $toPay ],`
 ProfileController.php:497 `method=> \Mollie\Api\Types\PaymentMethod::IDEAL` 
Kan ik morgen wel doen

**Comment by robinklaassen** [comment]
Let even op, betaling gebeurt nu op **twee** plekken: in de `RegistrationController` en in de `ProfileController`. Dit omdat een deelnemer voor het eerst op kamp kan gaan (met een nieuwe inschrijving in het systeem) of voor een latere keer (vanuit een bestaand account). Ik zou de code om te betalen graag op één plek zien (DRY), vandaar dat ik het refactoren er graag bij zou zien.
