### ISSUE TITLE
Preferred pronouns opnemen in profiel

### ISSUE THREAD

**Issue by robinklaassen** [robinklaassen/aas2#290]
We hebben recent meer gender opties toegevoegd, maar de voornaamwoorden nog niet goed meegenomen. Als je nu bijv. non-binair invult, wordt er in formulieren zoals de deelnemersenquête naar je verwezen als 'haar'. Terwijl je misschien dan net zo goed 'hem' genoemd wil worden.

Dus misschien moeten we die voornaamwoorden ook op het profiel zetten. Waarbij we met defaults kunnen werken voor iedereen die dat niet handmatig aanpast.

**Comment by blackshadev** [comment]
Ik dacht dat ik alle voornaamwoorden had vermeden. Ik zelf zou in het systeem zelf alle voornaam woorden vermijden, want het is niet nodig. Je kan altijd de zin ombouwen om het over "de deelnemer" te hebben. Dat maakt de code echt beter te doen.

Verder lijkt me het veldje nog steeds een prima toevoeging als extra informatie naar de leiding. Maar het lijkt me niet super relaxed om die ook intern te gebruiken.

**Comment by robinklaassen** [comment]
Oké nou ze zitten kennelijk nog in de deelnemerenquête: "Wat vind je van hoe hij/zij de stof uitlegt" enzo. Op zich prima om dat ook om te bouwen om het over 'de leiding' te hebben, is ook de snelste fix.
