### ISSUE TITLE
HSTS aanzetten

### ISSUE THREAD

**Issue by blackshadev** [robinklaassen/aas2#30]
Voor veiligheid is het fijn om HSTS aan te zetten op de apache server en ons aan te mensen voor HSTS preloading.

**Comment by blackshadev** [comment]
Preloading is een issue want er zijn wat subdomeinen van anderwijs (zoals wiki) die geen TLS hebben. En dat is dan verplicht. De enige optie is dan om een wildcard certificaat aan te vragen.

**Comment by robinklaassen** [comment]
HSTS aangezet op www.- en aas2.anderwijs.nl via de `.htaccess` files.
