### ISSUE TITLE
Restyle vakdekkingschecker

### ISSUE THREAD

**Issue by robinklaassen** [robinklaassen/aas2#34]
Lage prio, meer een idee dat ik had toen ik ernaar keek

- In plaats van symbolen, kleuren gebruiken voor de status (kleur de tabelregels): groen voor OK, rood voor onvoldoende leiding, geel voor onvoldoende niveau
- Leiding en deelnemers direct uitschrijven in de tabel, gesorteerd op niveau, in plaats van als een tooltip achter een cijfer.

**Comment by blackshadev** [comment]
Lijkt mij een simpele issue, wellicht een goede begin voor nieuwe mensen die hun steentje bij willen dragen
