### ISSUE TITLE
Unit tests voor kernfunctionaliteit

### ISSUE THREAD

**Issue by robinklaassen** [robinklaassen/aas2#35]
Nu er automatisch getest wordt middels Travis, lijkt het me zaak om unit tests toe te voegen om de stabiliteit van het systeem te verzekeren. Laten we beginnen met de kernfunctionaliteit. Daaronder versta ik:

- [x] Registratie leiding
- [x] Registratie deelnemer
- [x] Login
- [x] Leden-, deelnemer- en evenementoverzichten bekijken
- [x] Op kamp gaan vanuit profiel (leiding)
- [x] Op kamp gaan vanuit profiel (deelnemer)
- [x] Mollie betalingen (opgepakt in #27 )
- [x] Vakdekkingschecker
- [x] De JSON API's voor de Anderwijs website

Suggesties voor aanvullingen zijn zeker welkom.

**Comment by blackshadev** [comment]
Ik wilde de volgende dingen oppakken vanuit #27 
- Registratie van deelnemers
- Op kamp gaan vanuit je profiel 
- Mollie betalingen 

Je kan ook testen op welke emails er verzonden worden bij bepaalde acties, maar daarvoor moeten het wel de "nieuwe" emails zijn die je opbouwt a.h.v een class etc (althands, dat is de enige info die ik erover kan vinden).

**Comment by robinklaassen** [comment]
Ja dat van die emails had ik ook gezien. Ik stel voor dat we die in dit issue buiten beschouwing laten en een apart issue opvoeren om de mails te refactoren en te testen.
