### ISSUE TITLE
Update Carbon package to 2.0

### ISSUE THREAD

**Issue by robinklaassen** [robinklaassen/aas2#37]
Het php package `nesbot/carbon` gooit via composer de waarschuwing dat versie 1 nu deprecated is en iedereen naar versie 2 moet. Carbon is een dependency:

```
$ php composer.phar why nesbot/carbon
khill/lavacharts   3.0.8    requires  nesbot/carbon (~1.14)
laravel/framework  v5.8.18  requires  nesbot/carbon (^1.26.3 || ^2.0)
```

Het lijkt me goed om carbon expliciet te updaten en te controleren dat de `lavacharts` dependency (die uit mijn hoofd gebruikt wordt om de resultaten van de enquêtes weer te geven, zie de `ReviewsController.php`) blijft functioneren (en alle andere zaken natuurlijk ook - hopelijk zijn er geen grote wijzigingen aan de syntax gemaakt).

Meer over Carbon 2 in core Laravel: https://laravel-news.com/carbon-2-laravel

**Comment by robinklaassen** [comment]
Ik heb een comment achtergelaten bij een relevant issue op de github van lavacharts: https://github.com/kevinkhill/lavacharts/issues/302

Ik heb echter niet het gevoel dat dit package nog goed gemaintained wordt, dus mogelijk wordt het switchen naar een andere charting library (en misschien dan maar gelijk 1 charting library gebruiken voor heel AAS, want nu heb ik er minstens drie verschillende in zitten :P)

**Comment by blackshadev** [comment]
Lijkt me goed, hopelijk werkt carbon 2 zonder al te veel gezeur, Maar als het moet kan ik in D3 wel mooi spul maken, dat heb ik al meer dan eens gemaakt. Is wel even werk, maar erg leuk en leerzaam. 
Daarnaast zijn er vast ook andere pakketten  binnen php en laravel hoor.

**Comment by robinklaassen** [comment]
De auteur van Lavacharts heeft vandaag een PR gemerged die de Carbon versie omhoog gooit, dus met een beetje mazzel kunnen we dit issue nu zonder al teveel wijzigingen afronden :)
