### ISSUE TITLE
AVG: akkoord met privacyverklaring

### ISSUE THREAD

**Issue by robinklaassen** [robinklaassen/aas2#39]
SInds 25 mei 2018 is de AVG van kracht. Rond die tijd is aan de inschrijvingsformulieren in AAS een vinkje toegevoegd dat je toestemming geeft dat Anderwijs je gegevens behandelt volgens ons privacystatement. Heel formeel moeten gebruikers van AAS die voor die tijd al bestonden, ook nog hun toestemming geven. Bijvoorbeeld met een popup en een knop die ervoor zorgt dat je toestemming wordt geregistreerd in de database (met datum, lijkt me).

**Comment by blackshadev** [comment]
@robinklaassen Weet je precies welke datum je het vinkje aan de inschrijving had toegevoegd? Dan kan ik het veldje voor die mensen vullen met hun registratie datum, en anders krijgt iedereen die pop-up nogmaails bij het inloggen.
