### ISSUE TITLE
Dubbele inschrijvingen van deelnemers voorkomen

### ISSUE THREAD

**Issue by robinklaassen** [robinklaassen/aas2#41]
Het gebeurt helaas nog wel vaak dat een deelnemer zich meerdere keren inschrijft en we dus twee of drie keer dezelfde `Participant` hebben staan (met allemaal hun eigen user). Is weer gedoe voor de administratie om het op te schonen dus dat willen we natuurlijk graag anders.

Ik heb nog niet helemaal scherp waar dit allemaal mis zou kunnen gaan, maar wat ik in ieder geval wel gezien heb is dat je na inschrijving (en je bent op het bevestigingsscherm gekomen) op de back button van je browser kunt rammen en dat dan je input er nog staat, en dat is niet de bedoeling. Dus dat moet sowieso worden gefixt en daarnaast lijkt een algehele sanity check op de technische inschrijvingsprocedure wel een gezond plan.

**Comment by blackshadev** [comment]
Misschien moeten we het proberen te reproduceren. 

Wat ik sowieso al eens heb gemerkt dat het versturen van mails aardig sloom is, dus men kan ongeduldig zijn en in de tijd die men moet wachten (zeg 4 seconde) de vorige knop drukken of verversen ofzo. Dan krijg je sowieso dubbelen inschrijvingen. 

Een idee is om een van de invoer opties uniek te maken, eg. voornaam + achternaam + email ouders? Een andere oplossing is om laravel de mails te laten [queuen](https://laravel.com/docs/5.8/mail#queueing-mail) i.p.v. direct versturen, dat scheelt een hoop  qua snelheid, wel betekend het dat de stack iets ingewikkelder wordt. Maar het maakt ook meer mogelijk, zie 
 de [laravel docs over queuing](https://laravel.com/docs/5.8/queues) voor meer info.

**Comment by robinklaassen** [comment]
Ik betwijfel of het versnellen van mails veel gaat uitmaken. In mijn ervaring gaan de mails snel genoeg, zodat als je klaar bent met het lezen van de tekst op het 'bedankt voor je inschrijving' scherm de mail allang is aangekomen. Die paar seconden winst die je mogelijk kan pakken, gaan weinig doen denk ik.

Ik zou het graag reproduceren maar ik heb af en toe moeite met in het hoofd van de ouder van een deelnemer kijken :')

Unieke sleutel op invoervelden zetten is misschien wel een goed idee. We hadden natuurlijk eerder al het idee van (unieke) emailadressen ipv usernames te gebruiken, afgeschoten, maar dit is wellicht een alternatief. Moeten we even goed nadenken over welke velden dat zijn. Plus ik vind het dan ook wel erg belangrijk dat de experience zo vloeiend mogelijk is... want mensen zijn na een jaar gewoon hun inlog vergeten en daar moeten we het systeem op bouwen.

De 'password reset' optie bij het inloggen vraagt nu om je geboortedatum ter verificatie. Misschien moeten we dat eruit slopen en alleen maar op email basis doen, dan issie al wat toegankelijker.

Nou ja, zomaar wat ideeën, andere zaken zijn urgenter wat mij betreft.

**Comment by blackshadev** [comment]
Wat betreft de emails, ik bedoel niet de tijd die de mail onderweg is, ik bedoel de tijd die het nodig is om te versturen. Dus dat is vanaf dat je een form submit naar de backend tot dat je je  'bedankt voor je inschrijving' krijgt. Ik denk dat daar aardig wat tijd tussen zit, althans op test sowieso , maar ik verwacht dan in productie eigenlijk ook wel. 

Misschien moeten we een keer wat testen op productie uitvoeren om hier meer inzicht in te krijgen.

**Comment by robinklaassen** [comment]
To do: losse issue maken over mail queue implementeren en hieraan linken.

**Comment by blackshadev** [comment]
Ik sluit dit issue, tot dat we merken dat we hier weer last van hebben
