### ISSUE TITLE
Mailinglijsten voor ervaren trainers (bestaande + oud-leden)

### ISSUE THREAD

**Issue by robinklaassen** [robinklaassen/aas2#46]
Bij 'Lijsten' hebben we een tabblad 'ervaren trainers' met een tabel. Dit is niet heel makkelijk in het gebruik, dus ik wil hier een makkelijk te kopiëren mailinglijst aan toevoegen. Dit idee heb ik per mail besproken met de trainingscommissie van afgelopen jaar en het bestuur, en besloten om de lijsten ook op te splitsen in huidige leden (aspirant/normaal/info) en oud-leden.

Het idee voor de toekomst is ook om, als iemand aangeeft niet meer benaderd te willen worden voor trainingen, het vinkje 'ervaren trainer' bij deze persoon weg te halen zodat hij/zij niet meer in de mailinglijst staat. Maar dat is iets voor de betreffende commissie of contactpersoon.

Ik zal deze binnenkort zelf oppakken wanneer ik tijd heb :)

**Comment by blackshadev** [comment]
Dus als ik het goed begrijp:
Er is een bestaande lijst met 'ervaren trainers' beheert door de trainingscommisie? 

En je wil 2 dingen toevoegen
 - [ ] Kopie functie zodat je de emails als lijst makkelijk kan kopiëren
 - [ ]Beter te beheren voor de trainer commissie
 - [ ] Vinkje voor de leden die door de trainers als ervaren zijn aangemerkt om te opt-outen

**Comment by robinklaassen** [comment]
De bestaande lijst wordt nu al gegenereerd, er is een vinkje bij 'Leden' met 'Ervaren trainer'. Die blijft gebruikt worden. Dus het is meer:

- [] Splitsen van ervaren trainers overzicht in bestaande en oud-leden
- [] Toevoegen van emailadressen als lijst voor deze twee nieuwe lijsten
