### ISSUE TITLE
'Nieuw evenement' gooit 404

### ISSUE THREAD

**Issue by robinklaassen** [robinklaassen/aas2#55]
Gemeld via de mail door Liesbeth. Het pad `/events/create` gooit een onverwachte 404.

Het lukt mij nog niet om dit te fixen. Met `php artisan route:list` krijg je een lijst van alle geregistreerde routes en waar ze heen verwijzen en daar staat de betreffende route gewoon netjes bij. Controller method bestaat ook. En `php artisan route:clear` (om de cache te legen) helpt ook niet.

Nieuwe participants of members aanmaken werkt wel. En die routes worden ook via `Route::resource` gedefinieerd.

Kortom: moeilijk.

**Comment by blackshadev** [comment]
on it
