### ISSUE TITLE
Nieuw declaratiesysteem

### ISSUE THREAD

**Issue by Linths** [robinklaassen/aas2#6]
Declaratiesysteem: nieuwe versie implementeren
@robinklaassen graag verduidelijking

**Comment by robinklaassen** [comment]
Ik heb ooit (jaar of twee terug alweer) een nieuw declaratiesysteem geschreven, de source code daarvan is al deel van AAS: het wordt alleen nog niet gebruikt.

Het huidige (oude) declaratiesysteem is een formulier, dat na het invullen de informatie bundelt en de pdf + bijlagen in een email naar de penningmeester stuurt.

Het nieuwe declaratiesysteem bewaart iedere declaratie als een record in de database, met verwijzing naar opgeslagen files op disk, zodat je kunt terugzoeken wat je hebt ingediend en wat de status ervan is (i.e. heeft de penningmeester het al verwerkt). Voor de penningmeester is er een overzichtelijk dashboard gemaakt.

Je kunt het geheel bekijken via `/declarations` in je lokale omgeving.

Wat er moet gebeuren is dat de functionaliteit moet worden getest en eventueel verder uitgebreid, en in overleg met de penningmeester moet het live gezet worden.

**Comment by blackshadev** [comment]
done in #115
