### ISSUE TITLE
vriendelijkere wachtwoord resets

### ISSUE THREAD

**Issue by blackshadev** [robinklaassen/aas2#60]
Momenteel genereert de wachtwoord reset  een willekeurig wachtwoord, maar deze zijn niet bepaald ouder vriendelijk.
Vermijd 0 , o en O. 1 I i, U, u V vanwege duplicaten.
Versimpel het alfabet naar alles wat op een mobiel toetsenbord zichtbaar is: lowercase cijfers en punten

**Comment by blackshadev** [comment]
@robinklaassen Ik wil deze wel doen als we het eens zijn over de oplossingsrichting ;)

**Comment by robinklaassen** [comment]
Ja is wat mij betreft eenvoudig. In de `RegistrationController` wordt nu het password gegenereerd, apart voor leiding en deelnemers. Dat moet naar 1 plek en daar moeten de vervelende characters uit die string.

We kunnen ook fancyer doen met een aparte PHP library voor password generation maar dat voegt denk ik niet veel toe.

Komt dit overeen met jouw beeld?

**Comment by blackshadev** [comment]
@robinklaassen check. Dat centraliseren is prima, een lib lijkt me overkill, want dit is best simpel. Will do it later

**Comment by robinklaassen** [comment]
Oh, ik bedenk me nu dat de **resets** worden geregeld in de `PasswordController`. Dus de definitie van een nieuw password staat nu op drie plekken, dat moet terug naar één. Misschien een static method op het User model.
