### ISSUE TITLE
Exporteren deelnemersinfo foutmelding

### ISSUE THREAD

**Issue by blackshadev** [robinklaassen/aas2#63]
Ivo (van kantoor commissie) loopt tegen een probleem aan bij de deelnemerinfo export van het winterkamp

![Deelnemer info export boem](https://user-images.githubusercontent.com/2979104/70688196-6f47ff80-1cb1-11ea-99aa-179798ccadc7.png)

**Comment by blackshadev** [comment]
> Goedenavond beste AASbazen,
> 
> Zojuist probeerde ik de deelnemersinfo voor winterkamp te exporteren, maar dingen doen boem...
> Ik ben naar de pagina van het winterkamp gegaan en op export geklikt. Dan gaat er iets mis, zoals in de bijlage.
> Zouden jullie hier naar kunnen kijken? :)
> Dit gebeurt trouwens zowel in chrome als in internet explorer. Weet niet of dat nog iets helpt...
> 
> Groeten,
> Ivo

**Comment by robinklaassen** [comment]
Probleem is dat een van de deelnemers op kamp geen vakken had staan, daar zal dus ergens een index error op gegooid zijn. Lijkt me goed om een kleine patch te maken hiervoor. Nog chiller zou zijn om onder test te zetten, maar dan moeten we even kijken hoe we dat handig doen.
