### ISSUE TITLE
dompdf niet compatible met php7.4

### ISSUE THREAD

**Issue by blackshadev** [robinklaassen/aas2#68]
dompdf is niet compatible met php7.4 . Een gerelateerde issue heb ik hier gevonden:

https://github.com/dompdf/dompdf/issues/2003

Misschien is het een kwestie van later update als de issue is opgelost.

Voor nu hebben we nog geen problemen, want productie gebruikt php 7.2

**Comment by robinklaassen** [comment]
Dompdf 0.8.4 heeft dit issue verholpen, zie ook de (inmiddels gesloten) gelinkte issue. Hoe graag/snel wil je productie upgraden naar php 7.4?

**Comment by blackshadev** [comment]
Goed om te weten! Ik denk niet dat het haast heeft, verder.

**Comment by blackshadev** [comment]
Robin K upgraded to 7.3, because owncloud is not is not yet complient  see https://github.com/owncloud/core/issues/36509

**Comment by robinklaassen** [comment]
We zijn inmiddels geupgrade
