### ISSUE TITLE
Rollensysteem maken

### ISSUE THREAD

**Issue by Linths** [robinklaassen/aas2#7]
Dit rollensysteem zou verschillende organisatierollen erkennen binnen Anderwijs. Denk aan kampcommissie, kantoorcommissie, bestuur, AASbaas, etc. Deze hebben verschillende soorten rechten, waardoor bepaalde functionaliteit wel/niet beschikbaar wordt.

### Beleid  
Er moet bepaald worden welke rollen en welke rechten er zijn. **Wie ziet welke pagina?**
### Implementatie  
Rollen moeten aangemaakt kunnen worden en gedefinieerd worden.
_Note van @robinklaassen: misschien met een plugin?_

**Comment by blackshadev** [comment]
[on it](https://github.com/blackshadev/aas2/tree/feature/roles)
@robinklaassen  als men straks in code (blade.php , controllers of elders) gaan checken op rollen, is het hanger om dat op een bepaalde "tag" te doen , dan kan men namelijk de rol een leuk naampje geven en hoef je niet elke keer je code te veranderen. Ook als IDs een keer uit de pas lopen is dat geen probleem zeg maar. Of had je andere ideeën?

**Comment by blackshadev** [comment]
Ik ben bijna klaar met de code maar , even wat vraagjes. 
1. Wat voor rollen willen jullie? 
2. Wat willen jullie dat de rollen kunnen?
3. Willen we functies rol gebonden maken of willen jullie er nog een laagje tussen zodat je dat beter te manage is maar rotter te code (keuzes)
4. Willen we het rollen systeem en welke functies die hebben voor of na de merge doen?

Om 4 toe te lichten:
Als we alles voor de merge doen dan moet ik alles van te voren weten
En als we het erna vullen dan komen er mondjes maten functies bij/ter vervallen voor mensen naar maten we dingen aan rollen binden, maar dan kunnen misschien meer mensen helpen.

**Comment by blackshadev** [comment]
Ik wil nog policies introduceren, maar dan moet ik wel weten welke rechten men moet kunnen verlenen, ik zal een opsetje maken en die delen zodat het Bestuur van anderwijs of een van de commissies daar hun hun zegje over kunnen doen voor een definitieveren invullen. Uiteraard kan dit later ook nog gewijzigd worden.

**Comment by blackshadev** [comment]
Hee Ik heb graag wat input nodig van mensen betreffende het rollen systeem. Ik zal hieronder uitleggen wat Robin en ik bedacht hebben om context te geven en helemaal onderaan wat ik concreet wil hebben qua info. 

## context
Zoals ik het heb bedacht kent het systeem 3 niveaus waarmee we in AAS beleid gaan voeren: gebruikers, rollen en rechten. een gebruiker heeft 0 of meer rollen en een rol heeft 0 of meer rechten. Daarmee heeft een gebruiker 0 of meer rechten. 

## Voorbeelden van rollen:
 1. AAS-Baas (de super baas admin van het systeem, beter bekent als @robinklaassen )
 2. Bestuur
 3. Kamp-CI
 4. Kantoor-CI
 5. One-CI 
 6. Penningmeester
 7. Leiding
 8. Deelnemer 

## Voorbeelden van rechten
 1. Inzien alle events 
 2. Wijzigen events
 3. Aanmaken van events
 4. Verwijderen van events
 5. Alle deelnemers zien van events
 6. Deelnemerlijst exporteren van events
 7. Inzien alle Leden
 8. Wijzigen van deelnemer profielen
 9. Verwijderen van deelnemer profielen
 10. Aanmaken van deelnemer profielen
 11. Rollen wijzigen van leiding

### Uitzonderingen
Nu denk je, mooi, maar wat als ik een uitzondering op de regel heb? Zoals
 - Wat als leiding wel de deelnemers mogen zien die op hun kamp mee gaan. 
 - Of we willen niet dat iemand oude events kan verwijderen?
 - Of we willen wel dat als je deelnemer of leiding bent van een event je wel het event kan zien maar anders niet

Dat is allemaal geen probleem, helaas kunnen we dat niet via een UI beschikbaar maken en moeten we dat echt in zogeheten `Policies` coderen, maar het kan wel.

Dit gaat nogal ver, maar het idee is dat het voor iedereen duidelijk is wat een rol op enig moment inhoud en daarmee wat een gebruiker met die rol mag en kan doen.  Later gaan we het ook beschikbaar maken dat we deze invulling zelf in aan kunnen veranderen, dus als het bestuur dan wil dat de Kamp-CI helemaal niet meer events mag wijzigen, is dat 1 klik verwijderd . 

## Wat mis ik qua informatie
Nu wil ik heel graag dit allemaal invullen en maken, maar ik heb geen flauw benul wat voor rechten jullie allemaal willen, en nu kunnen robin en ik een hoop zelf invullen, maar misschien is het handig als het bestuur, of de vereniging daar ook even over mee denkt. 

Wat ik nodig heb is :
 - Een lijst aan Rollen 
 - Een lijst aan rechten
 - Een overzicht welke rol wat mag
 - Een overzicht aan uitzonderingen

Houd er rekening mee dat als men dit opstelt dat je ook een stapje terug moet doen, hoe iets nu is, is niet meer een gegeven als we dit willen invoeren. Zoals het zien van een deelnemer dat die gene betaald heeft, of zijn inkomensverklaring gevalideerd heeft, Dat zijn dingen die nu bedoeld zijn voor de `admin` maar nu is hier dus de gelegenheid om dit aan een recht te knopen

**Comment by robinklaassen** [comment]
Deze zit erin, eventuele toekomstige issues pakken we los op :)
