### ISSUE TITLE
Rollen systeem fixups

### ISSUE THREAD

**Issue by blackshadev** [robinklaassen/aas2#72]
Verzamel issue voor alle issues met de huidige rollen. Graag in een formaat waarin duidelijk is wat iemand niet kan en wel zou willen / moeten kunnen,  met daarin  door wie dit is opgemerkt.

De status kent de volgende waarde:
 - :heavy_check_mark: Klaar in productie
 - :white_check_mark: Staat klaar in repo 
 - :exclamation: Spoed
 - :pause_button:  In afwachting

| Status | Wie |  Rol | Rechten ( + erbij / - te veel) | Uitleg (door aasbaas) |
| --- | --- |  --- | --- | --- |
| :heavy_check_mark: | Robin vd L | Kamp-CI | Deelnemers - | Kamp-CI hoeft alleenmaar de deelnemende deelnemers te zien bij de kamp pagina, niet de deelnemers zelf |
|  :heavy_check_mark: | Robin vd L| Kamp-CI | Gebruikers - | Hij heeft het nooit gebruikt, waarom hij het uberhaupt kan zien weet ik niet, dat moet ik even onderzoeken. (wellicht voor password resets?). Edit: deze view komt in de toekomst te vervallen, maar dit was zodat je wachtwoorden wijzigen van leden en leden kon verwijderen. Dit heb ik nu bij de leden pagina zelf gezet en dan verwijderen we deze pagina gewoon. |
| :heavy_check_mark:  | Robin vd L | Kamp-CI | Punten - | Heeft hij niet nodig, maar is geen ramp. |
| :heavy_check_mark:  | Liesbeth, Nathalie | Bestuur | Leden + | Liesbeth heeft vernomen dat het bestuur nu geen adres gegevens van de leden meer kan zien, maar voor bestuurs uitjes / etentjes etc. is dat wat onhandig, daarnaast het is het bestuur, why not. | 
| :heavy_check_mark: | Iris | Normaal Lid | deelnemers - | Kunnen deelnemer basis informatie zien en via de index pagina van deelnemers ook prive info , kan nieuwe deelnemers aanmaken | 
| :heavy_check_mark: | Iris | Normaal Lid | locatie - | Kan alle info zien van locaties, update: Heb contact gegevens gescheiden van de basis info | 
| :heavy_check_mark:  | Iris | Normaal Lid | event - | Kan nieuw event invoeren  |
| :heavy_check_mark: | Bouchien | Promo | deelnemers + | Ze wil de deelnemende deelnemers zien en die ziet ze nu niet bij kampen. Edit: promoci ziet enkel de niet geplaatste deelnemers, als we onderscheid willen maken in wie wel en niet ongeplaatste deelnemers kan zien moet er een recht bij komen. Edit2: Ik heb een eigen lijst gemaakt met alle nieuwe deelnemer inschrijvingen voor promoci, met informatie zoals hoebij, datum, naam , kamp en of het de eerste kamp is voor de deelnemer  |
| :heavy_check_mark: | Fieke | Ranonkeltje | nieuwe rol | Nieuwe rol toevoegen voor de Ranonkeltje commissie, deze moet de lijst 'Ranonkeltje' kunnen zien voor het versturen van de Ranonkeltjes (zowel fysiek als digitaal). |

**Comment by robinklaassen** [comment]
Ik weet even niet wat normale leden nu kunnen zien van andere leden, maar een lijst met namen en @anderwijs mailadressen (ook nav mail Fieke) lijkt me in de basis wel zinvol.

**Comment by blackshadev** [comment]
Rol voor ranonkeltje is toegevoegd en die kan weer bij lijsten. 
Als normaal lid zou je wel bij de basis info van leden moeten komen, ik denk dat dat nu fout gaat. 

Momenteel zijn de volgende data beschikbaar onder het member::show:basic recht:  `Naam / Woonplaats / Hoe bij Anderwijs / Rijbewijs / Anderwijs email / Kampen & trainingen & activiteiten / Ranonkeltje digitaal  / Lid sinds` dat recht ga ik de members geven dan zou het weer goed moeten zijn

**Comment by blackshadev** [comment]
Fixed by merge
