### ISSUE TITLE
DataTables voor indexes met variabel aantal kolommen

### ISSUE THREAD

**Issue by robinklaassen** [robinklaassen/aas2#75]
De overzichtspagina's (van bijvoorbeeld leden, deelnemers, ...) gebruiken de Javascript library `DataTables` om er een interactieve tabel van te maken. De configuratie hiervan gaat per kolom met een array. Deze array verwijst naar de indices van de kolommen in de HTML.

Echter hebben we onze HTML nu veranderlijk gemaakt door de rollen. Hierdoor werkt de datatable nu bijvoorbeeld wel als ik lokaal ingelogd ben als `ranonkeltje`, maar niet als ik op mijn eigen live account inlog.

Ik wil deze op zich wel oppakken, maar even overleggen over de beste oplossingsrichting.

**Comment by blackshadev** [comment]
Ahh OK nooit opgevallen dat we zo een functie hadden.
Je kan js zelf de kolommen laten zoeken, dan werkt het wel gelijk op elke
pagina ziet dat je moet kloten met rollen en kolom namen. Check de
onderstaande docs, daar moet het mee lukken.
https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll
