### ISSUE TITLE
Same-origin policy aanhouden

### ISSUE THREAD

**Issue by Linths** [robinklaassen/aas2#8]
Bijvoorbeeld, er zit css in de blade.php bestanden.

[Uitleg wikipedia](https://en.wikipedia.org/wiki/Same-origin_policy). Vraag @VXLs voor meer kennis.

**Comment by blackshadev** [comment]
Met robin overlegt:

Momenteel worden er resources (css , js files, plaatjes en fonts) van CDNs gehaald (externe server speciaal gemaakt voor die files te verspreiden). Is vrij weinig mis mee om dit te gebruiken , maar netter (en veiliger) is om dit zelf lokaal op de AAS server te zetten. Zodat alle files op dezelfde plek staan (same-origin)

**Comment by blackshadev** [comment]
Ik sluit de ticket voor nu, mocht dit later wel een wens zijn kan hij altijd heropent worden
