### ISSUE TITLE
Nieuwe rol: vertrouwenspersoon

### ISSUE THREAD

**Issue by robinklaassen** [robinklaassen/aas2#83]
The tricky bit: het telefoonnummer van de VP moet zichtbaar zijn voor alle leden (en niet dat de VP andere nummers kan zien). Nog geen idee hoe we dat gaan doen. Over verdere invulling ben ik nog aan het praten met Ingeborg.

**Comment by robinklaassen** [comment]
@blackshadev ik begreep van Ingeborg dat deze prio moet krijgen omdat dit nodig is om gratis VOG's te blijven krijgen, en dat moet voor eind deze maand aangevraagd zijn. Wil je meedenken over hoe we dat telefoonnummer kunnen publiceren? De meest directe oplossing is om dit gewoon in de view af te vangen met een iets ingewikkeldere if/unless block, maar misschien weet jij iets netters.

**Comment by blackshadev** [comment]
Zie PR, daar heb ik alvast wat gehannest.

De rede voor een rol en niet een vinkje is omdat we hier dan weer makkelijker rechten op kunnen zetten. Ik zie namelijk een mogelijkheid dat het vertrouwenspersoon wel prive data en geheime comments moet kunnen zien. Daarnaast is het in lijn met de rest van het systeem, en ik moest het toch in de MemberPolicy gaan oplossen qua rechten, dus ik kon overal bij.

Ik heb alvast de MemberPolicy aangepast dat iedereen de vertrouwenspersoon kan inzien en ook zijn/haar telefoonnummer.

Het enige waar ik nog niet helemaal over uit ben:

 - Een manier om de vertrouwenspersoon te zien, want deelnemers kunnen niet bij de members.index
 - Misschien willen we niet alle data die dan op de member pagina staat openbaar stellen? Momenteel staat er: Geboortedatum (indien gepubliseert), Geslacht, Woonplaats, Telefoonnummer, Hoe bij Anderwijs, Ranonkeltje, Emailadres bij Anderwijs

**Comment by blackshadev** [comment]
Conclusie gesprek met Robin

- Deelnemers hoeven de vertrouwenspersoon niet in AAS in te zien, dit is een nice to have voor later. Want zij krijgen de gegevens door via email / brief.
- De huidige implementatie is prima met wat test en polish
