### ISSUE TITLE
Koppel kampen aan trainingen

### ISSUE THREAD

**Issue by Linths** [robinklaassen/aas2#9]
Meer wat voor AAS3. In AAS2 zijn kampen en trainingen beide "events", en zou je relaties ertussen moeten kunnen opslaan in de databases.

**Comment by robinklaassen** [comment]
Een mogelijke use case hiervoor kan zijn om aantal trainers toe te voegen aan de thermometer op de homepage. Met een match op basis van event codes / namen zou dit niet al te ingewikkeld moeten zijn.
