### ISSUE TITLE
Unit tests voor mails

### ISSUE THREAD

**Issue by robinklaassen** [robinklaassen/aas2#93]
N.a.v. PR #90 zijn we erachter gekomen dat het niet triviaal is om mails te unit testen, terwijl die wel een belangrijk deel vormen van de user experience. Zou dus fijn zijn als we daar een keer wel iets mee kunnen.

**Comment by blackshadev** [comment]
https://github.com/laravel/ideas/issues/405
Dit heb ik als resource gevonden, maar onze `mailable->viewData` is altijd leeg for some reason. Dus ik ben er nog niet uit. 

Een alternatief is een unit tests schrijven op de mailables zelf.

**Comment by blackshadev** [comment]
Ik heb een test op de ParticipantOnEventConfirmation Mailable geschreven en dat werkt best prima eigenlijk. @robinklaassen kan jij kijken of je het er mee eens bent? Dan kunnen we misschien unit tests schrijven op alle mailables?

## Todo

- [ ] internal/CoverageChangedNotification
- [ ] internal/MemberOnEventNotification
- [ ] internal/NewDeclaration
- [ ] internal/newMemberNotification
- [ ] internal/NewParticipantNotification
- [ ] internal/NewParticipantNotification
- [ ] internal/ParticipantEditedEventCourseInformation
- [ ] internal/ParticipantOnEventNotification
- [ ] members/MemberRegistrationConfirmation
- [ ] members/NewUserMember
- [ ] members/OnEventConfirmation
- [x] participants/OnEventConfirmation
- [ ] participants/NewUserParticipant
- [ ] participants/ParticipantRegistrationConfirmation
- [ ] ResetPassword
