### ISSUE TITLE
Lijstje voor PromoCI: Nieuwe leiding

### ISSUE THREAD

**Issue by blackshadev** [robinklaassen/aas2#94]
Aangevraagd doot Bouchien van PromoCI

Originele tekst:
> Kunnen de inschrijvingen van nieuwe leiding ook zichtbaar gemaakt worden voor de promocie? 
(Zo kan ik zien of ik nog contact met iemand moet opnemen via de vacaturebank of dat dat al loopt via kantoor/kamp/betsuur/...)

Een lijstje van leidingen (Members) die zich in het afgelopen half jaar hebben aangemeld met daar in 
- naam
- wanneer aangemeld (Lid sinds)
- via wat kwam de aanmelding (hoebij)

Het gaat dus om nieuwe leidingen, niet inschrijvingen van bestaande leidingen.

Dit betekend dat de promoCI ook recht moet krijgen op het veldje "lid sinds" van members

**Comment by robinklaassen** [comment]
Er is volgens mij al een lijst 'aspiranten', wellicht kunnen we die aanpassen voor dit doel, denk niet dat die voor heel veel andere dingen gebruikt wordt (was volgens mij origineel voor de penningmeester om mensen facturen te sturen). Of had jij een heel ander idee in je hoofd?

**Comment by blackshadev** [comment]
Nou de lijstjes zitten aan rollen remember. Dus mijn gedachte was: Nieuw lijstje voor promoci: OK. 

Ik denk vooral dat we dit gescheiden moeten houden omdat 2 verschillende partijen (penningmeester vs promoci) ongeveer het zelfde willen voor een ander doel. Dus als 1 van de 2 later net wat anders wil zien, is dat vervelend om bij te houden en te fixen dan als we het nu als 2 apparte lijsten behandellen.

**Comment by robinklaassen** [comment]
Fair enough, lijkt me een prima aanpak
