### ISSUE TITLE
Intresses en vaardigheden

### ISSUE THREAD

**Issue by blackshadev** [robinklaassen/aas2#96]
Men wil een "knopje" met intresses en vaardigheden. 
Maar ik mis info, 

- Intresses en vaardigheden als één invoer of als twee lossen?
- waar / bij welke entiteit
- wat voor veld: Tekst? 
- Beschrikbaar bij registratie en verplicht of optioneek? Of enkel bij profiel en optioneel?

**Comment by robinklaassen** [comment]
Gesloten door #112
